# Generated by Django 6.0.4 on 2026-05-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='chat_history',
        ),
    ]
