# Generated by Django 6.0.4 on 2026-05-04 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_history_chat_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_history',
            name='index',
        ),
        migrations.AddField(
            model_name='chat_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
    ]
