# Generated by Django 6.0.5 on 2026-05-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_delete_chat_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
